name: CI

on: 
  workflow_dispatch:
    inputs:
      target:
        description: "Where to deploy"
        type: choice
        options: [staginh, production]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployed to ${{ inputs.target }}"
